on: [push]
jobs:
  build-flutter-arm64:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v3
      - name: Build Flutter
        run: | 
          git clone -b master https://github.com/flutter/flutter.git
          cd flutter
          export PATH="$PATH:$PWD/flutter:$PWD/bin"
          ls
          chmod +x *
          flutter doctor
          cd ..
          env GZIP=-9 tar cvzf flutter.tar.gz flutter
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: flutter.tar.gz
