on: [push]
jobs:
  build-flutter-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Flutter
        run: | 
          git clone -b master https://github.com/flutter/flutter.git
          cd flutter
          export PATH="$PATH:$PWD/flutter:$PWD"
          ls
          chmod +x *
          flutter doctor
          cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
           name: arm64-release
           path: flutter
