on: [push]
jobs:
  build-flutter-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Flutter
        run: | 
           curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.7.0-stable.tar.xz
           tar -xvf flutter_linux_3.7.0-stable.tar.xz flutter/bin/cache/artifacts/engine/linux-x64/shader_lib
           tar -zcvf flutter.tar.gz flutter/bin/cache/artifacts/engine/linux-x64/shader_lib 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
           name: arm64-release
           path: flutter.tar.gz
